name: Cypress tests
on:
  push: 
    branches:
      - master
      - main
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v3
        with:
          record: true
          start: npx cypress run
